# Generated by Django 4.0.2 on 2022-03-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='email_clente',
            new_name='email_cliente',
        ),
    ]
