# Generated by Django 4.0.2 on 2022-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='scheduling_states',
            field=models.CharField(choices=[('CONF', 'CONF'), ('UNCO', 'UNCONF'), ('EXEC', 'EXEC'), ('CANC', 'CANC')], default='UNCO', max_length=4),
        ),
    ]
