# Generated by Django 4.0.2 on 2022-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_agendamento_scheduling_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='scheduling_states',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='states',
            field=models.CharField(choices=[('CONF', 'CONFIRMATED'), ('UNCO', 'UNCONFIRMATED'), ('EXEC', 'EXECUTED'), ('CANC', 'CANCELED')], default='UNCO', max_length=4),
        ),
    ]
