# Generated by Django 4.0.2 on 2022-04-07 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0006_remove_agendamento_scheduling_states_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('nivel_fidelidade', models.IntegerField()),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
