# Generated by Django 4.0.2 on 2022-04-07 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0007_fidelidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidelidade',
            name='nivel_fidelidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fidelidade',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidade', to=settings.AUTH_USER_MODEL),
        ),
    ]
