# Generated by Django 4.0.2 on 2022-04-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0008_alter_fidelidade_nivel_fidelidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddConstraint(
            model_name='fidelidade',
            constraint=models.UniqueConstraint(fields=('nome_cliente', 'prestador', 'nivel_fidelidade'), name='fidelidade_unique'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.estabelecimento'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
