# Generated by Django 4.0.2 on 2022-04-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_servicos_funcionarios_funcionario_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='servico',
            field=models.CharField(max_length=300),
        ),
    ]
