# Generated by Django 4.0.2 on 2022-04-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0011_alter_servicos_servico"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="estabelecimento",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                to="agenda.estabelecimento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="agenda.servicos",
            ),
        ),
    ]
