# Generated by Django 4.0.2 on 2022-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_agendamento_estabelecimento_agendamento_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='servicos',
            new_name='servico',
        ),
        migrations.AlterField(
            model_name='servicos',
            name='servico',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
